# Generated by apps/cli/packaging/render-formula.ts in tportio/developers-center.
# Do not edit by hand; the next CLI release overwrites this file.
class OndaDeveloperCenter < Formula
  desc "Configure the ONDA Developer Center portal from a terminal or an AI agent"
  homepage "https://developers.tport.dev/docs/cli"
  version "0.1.0"

  on_macos do
    on_arm do
      url "https://github.com/ondame/homebrew-tap/releases/download/cli-v0.1.0/ondadc_0.1.0_darwin_arm64.tar.gz"
      sha256 "880255f2f6314e9894d6eddbcc4b6ea2a72350ab26cc9d6f7601faf868d96f65"
    end
    on_intel do
      url "https://github.com/ondame/homebrew-tap/releases/download/cli-v0.1.0/ondadc_0.1.0_darwin_amd64.tar.gz"
      sha256 "f354b65ebf4636fe1563bfebd4fcec359813d754b21bb6073849ef59906bd2b4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ondame/homebrew-tap/releases/download/cli-v0.1.0/ondadc_0.1.0_linux_arm64.tar.gz"
      sha256 "744b50bd90e338f7525754e780132e1ee139e2075e31479b2842580c16623094"
    end
    on_intel do
      url "https://github.com/ondame/homebrew-tap/releases/download/cli-v0.1.0/ondadc_0.1.0_linux_amd64.tar.gz"
      sha256 "48748577c2aca0a6a471fe0a307c03507808b555d3ea290046ac5b10c940cdb0"
    end
  end

  def install
    bin.install "ondadc"
    generate_completions_from_executable(bin/"ondadc", shell_parameter_format: :cobra)
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ondadc version")
  end
end
